### ISSUE TITLE
Layout Broken

### ISSUE THREAD

**Issue by ghost** [EliverLara/Squared#1]
Hello!

I want share a layout bug when I delete files/folders.

![Screenshot from 2024-10-27 10-46-44](https://github.com/user-attachments/assets/ac28b197-cbf2-4f11-8633-cd2464eb421f)

In this case, the buttons continue square when I hover mouse above it, but how you see, this component that info the delete files/delete, still is rounded.

Follow my system configuration:

![image](https://github.com/user-attachments/assets/4d62689e-8773-4ad6-8c7b-1f4e15ed9a3c)

**Comment by umnachasha** [comment]
i think that's the libadwaita's issue

**Comment by EliverLara** [comment]
That was fixed in 7038471f48b8cda46648777ca211109ac0c83917
