### ISSUE TITLE
The grid view/listvew button of the Nautilus file manager bar does display the grid view icon properly

### ISSUE THREAD

**Issue by mreyesza** [EliverLara/Squared#2]
Dear EliverLara,
     I installed both Nordic and Square themes in a Debian 12. The themes look really nice. However the grid view button is not displayed properly in the Nautilus file manager when configuring Nordic icon set in the Tweak tool. This icon is displayed properly when  switching the icon set to the default setup.

    Please refer to the screenshots attached bellow:

    1) Screenshot when selecting the Nordic icon set:

![image](https://github.com/user-attachments/assets/4ef5acb7-6106-4db9-8560-3ee337962807)

    2) Screenshot when selecting the default icon set:

![image](https://github.com/user-attachments/assets/dd59162f-7fdb-49f7-9c5d-67ddfd676847)

Many thanks, 

Miguel

**Comment by EliverLara** [comment]
Hi, Where did you donwload the Nordic icons?

**Comment by mreyesza** [comment]
Hello,

    thanks for coming back. The icons are downloaded in the .icons folder within my home folder as shown in the picture below?

![image](https://github.com/user-attachments/assets/e28c3028-281b-4402-87f5-2a21d02fa0c2)


Regards,

Miguel

**Comment by EliverLara** [comment]
I think that's an issue with the inherits entry in the index.theme file, try replacing that line for an icon theme you already have installed: `inherits=some_icon_theme_name`

**Comment by mreyesza** [comment]
Hello, you were right. I changed the Inherits property to fallback on Adwaita and now the icon is displayed fine.

Find below the change introduced in the index.theme file as suggested:

```
[Icon Theme]
Name=Nordic
Comment=Folders for Nordic gtk theme.
#Inherits=Papirus-Dark,breeze-dark,Zafiro,ubuntu-mono-dark,Mint-X,elementary,gnome,hicolor
Inherits=Adwaita
```

This is the result:

![image](https://github.com/user-attachments/assets/7dab9d84-bd13-4bd5-b606-d9a392e0004c)

Many thanks for your support!

Miguel
